#!/usr/bin/python3

import os
import time

#Terminal GUI Console
def main():
    os.system("clear")
    print("Welcome To Minetest Control Management(MCM)")
    print("[1]System Console               [2]Backup/Restore")
    print("[3]System Configs               [4]Software Update")
    print("{Q} Exit")
    welcome = input("Type Youre Option: ")
    
    if welcome == "1":
        System_Console()
    elif welcome == "2":
        BRS()
    elif welcome == "3":
        SC()
    elif welcome == "4":
        Upgrade()
    elif welcome == "Q" or welcome == "q":
        os.system("clear")
        print("Thank You For Using MCM")
    else:
        system("clear")
        break

#System Console
def System_Console():
    os.system("clear")
    print("[1] Start                  [2]Stop")
    print("[3] View Console           [4]Main Menu")
    console = input("Type Youre Option: ")

#Start Minetest (Please Change Script path if using ln -s)
    if console == "1":
        os.system("clear")
        os.system("screen -dmS Minetest -m bash /home/darkwar/Desktop/minetest/bin/Start.sh")
        System_Console()

#Stop Minetest
    elif console == "2":
        os.system("clear")
        os.system("screen -XS Minetest quit")
        os.system("clear")
        System_Console()

#Views Minetest Console    
    elif console == "3":
        os.system("clear")
        print("To Exit Ctrl + a Ctrl + D")
        time.sleep(4)
        os.system("screen -r Minetest")
        System_Console()
    
#Goes Back to Main Menu    
    elif console == "4":
        os.system("clear")
        main()
        
    else:
        os.system("clear")
        main()
        
#Backup And Restore System
def BRS():
    os.system("clear")
    print("Welcome To Backup And Restore")
    print("[1]Backup          [2]Restore")
    print("{Q} Main Menu")
    brs = input("Enter Option: ")
    if brs == "1":
        os.system("clear")
        os.system("bash backup.sh")
        os.system("clear")
        BRS()
    elif brs == "2":
        os.system("clear")
        os.system("bash restore.sh")
        os.system("clear")
        BRS()
    else:
        os.system("clear")
        main()
def SC():
    os.system("clear")
    print("Welcome To System Configs")
    print("[1] Adding Mods       [2]Removing Mods")
    print("[3] Minetest.conf     [4]World.mt")
    print("[5] Adding Textures   {Q} Exit")
    sc = input("Enter Option: ")
    if sc == "1":
        print("Paste Mod File here")
        url = input("Enter url: ")
        link = "cd ~/Desktop/minetest/mods && git clone "+url
        os.system(link)
        time.sleep(1)
        print("Please Reboot the Server\n Dont Forget to Edit the world.mt file")
        time.sleep(2)
        SC()
    elif sc == "2":
       print("Copy And Paste the Mod you dont want")
       time.sleep(1)
       os.system("ls ~/Desktop/minetest/mods")
       mod = input("Mod Name here: ")
       remove = "rm -fr ~/Desktop/minetest/mod "+mod
       os.system(remove)
       SC()
    elif sc == "3":
        os.system("nano ~/Desktop/minetest/minetest.conf")
        SC()
    elif sc == "4":
        os.system("nano ~/Desktop/minetest/worlds/world/world.mt")
    elif sc == "5":
        print("Paste Texture Here")
        url = input("Enter url: ")
        link = "cd ~/Desktop/minetest/textures && git clone "+url
        os.system(link)
        SC()
    else:
        os.system("clear")
        main()
def Upgrade():
    os.system("sudo apt update && sudo apt upgrade")
    os.system("bash updater.sh")



#Software Update Menu

